# Use the official TensorFlow Serving image as the base image
FROM tensorflow/serving:latest


# Install necessary packages
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    && apt-get clean

# Install Flask and other dependencies
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

# Copy the model to the model directory
COPY /model /models/model/1

# Copy Flask app files
COPY app.py /app.py
COPY templates /templates

# Copy the startup script
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Set environment variables
ENV MODEL_NAME=model

# Expose the default port TensorFlow Serving uses
EXPOSE 8501

# Run TensorFlow Serving
ENTRYPOINT ["tensorflow_model_server", "--rest_api_port=8501", "--model_name=model", "--model_base_path=/models/model"]
