# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python apps to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: ['classificating-images-cifar10', 'imageclassification']
        python-version: ['3.11', '3.12']
        client-id: ['AZUREAPPSERVICE_CLIENTID_5D00376C4D6F4BE2B4FF7EC818C3AB93', 'AZUREAPPSERVICE_CLIENTID_CCD4CBA7A0EC49AA8DCD81EAFDB45072']
        tenant-id: ['AZUREAPPSERVICE_TENANTID_EECED5B7BA7B40638D2767D856DA9DCD', 'AZUREAPPSERVICE_TENANTID_C2573DCDB231423FAC8F4F0110B3BFA8']
        subscription-id: ['AZUREAPPSERVICE_SUBSCRIPTIONID_B4D9391422D34C75BD0AF87F5E9C1771', 'AZUREAPPSERVICE_SUBSCRIPTIONID_8219DAB8A4C944E1A1195BD28DB9EABA']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses
